export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_CART_TO_USER = "ADD_CART_TO_USER";
export const GET_CART_ITEMS_USER = 'GET_CART_ITEM_USER';
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const ON_SUCCESS_BUY = "ON_SUCCESS_BAY";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_UPDATE_PROFILE = "CLEAR_UPDATE_PROFILE";


export const GET_PRODUCTS_BY_SELL = "GET_PRODUCTS_BY_SELL";
export const GET_PRODUCTS_BY_ARRIVAL = "GET_PRODUCTS_BY_ARRIVAL";
export const GET_PRODUCTS_BY_SHOP = "GET_PRODUCTS_BY_SHOP";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const CLEAR_PRODUCT_DETAIL = "CLEAR_PRODUCT_DETAIL";

export const ADD_BRAND = "ADD_BRAND";
export const BRANDS = "BRANDS";
export const ADD_WOOD = "ADD_WOOD"
export const WOODS = "WOODS";

export const GET_SITE_DATA = "GET_SITE_DATA";
export const UPDATE_SITE_DATA = "UPDATE_SITE_DATA";
